### ISSUE TITLE
invalid link in readme

### ISSUE THREAD

**Issue by maybeec** [mojohaus/servicedocgen-maven-plugin#13]
There is a link in the readme to http://www.mojohaus.org/servicedocgen-maven-plugin/ which does not point to a valid mojohaus page.

**Comment by jochenw** [comment]
Well, but the solution seems to be to publish docs, rather than fixing the link.
@hohwille: Could you act on that, please?

**Comment by hohwille** [comment]
@may-bee the link is correct but the site could not yet be published due to technical problems.
@jochenw I do not understand your comment in this context. Maybe you got the wrong github repository..

**Comment by hohwille** [comment]
Duplicate of #5 - closing.
